# Generated by Django 4.1.5 on 2023-04-05 17:54

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(upload_to=base.models.upload_path_handler_up),
        ),
    ]
