# Generated by Django 4.2.5 on 2023-09-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('Host', 'host'), ('Host', 'owner'), ('Host', 'guest')], default='Host', max_length=50),
        ),
    ]
