# Generated by Django 4.2.5 on 2023-09-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='No bio.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('Host', "I have a house/room and I'm looking for a roommate."), ('Owner', "I'm a property owner looking for tenants."), ('Guest', "I'm looking for a place to stay.")], default='Host', max_length=50),
        ),
    ]
