# Generated by Django 4.1.5 on 2023-04-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_roomphoto_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(max_length=800),
        ),
    ]
