# Generated by Django 4.1.5 on 2023-10-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_bio_alter_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='maps_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
