# Generated by Django 4.1.5 on 2023-04-15 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_notification_title_alter_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='trigger_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Trigger_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Target_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
