# Generated by Django 4.2.5 on 2023-10-02 01:05

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_property_maps_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='actId',
            new_name='rec_id',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='trigger',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='default_text',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='target_id',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='activity_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='activity_group',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='maps_link',
            field=models.CharField(blank=True, help_text='You may need to allow access to your location to access maps navigation.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='roomphoto',
            name='image',
            field=models.ImageField(upload_to=base.models.upload_path_handler_room_new),
        ),
    ]
