# Generated by Django 4.2.5 on 2023-10-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_actid_activitylog_rec_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='target_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_model',
            field=models.CharField(default='', max_length=255),
        ),
    ]
