# Generated by Django 4.1.5 on 2023-04-17 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_notification_options_user_matches_user_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairrequest',
            name='trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initializer', to=settings.AUTH_USER_MODEL),
        ),
    ]
