# Generated by Django 4.2.5 on 2023-10-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_activitylog_target_id_activitylog_target_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
