# Generated by Django 4.1.5 on 2023-04-28 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_pairrequest_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairrequest',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to=settings.AUTH_USER_MODEL),
        ),
    ]
