# Generated by Django 4.1.5 on 2023-04-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_like_options_alter_review_options_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='default_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='target_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
