# Generated by Django 4.1.5 on 2023-05-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_activitylog_default_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created']},
        ),
    ]
