# Generated by Django 4.1.5 on 2023-05-30 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_match_options_alter_home_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='requestsList',
            field=models.ManyToManyField(blank=True, null=True, related_name='room_requesters', to=settings.AUTH_USER_MODEL),
        ),
    ]
