# Generated by Django 4.1.5 on 2023-05-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_home_requestslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='requestsList',
            field=models.ManyToManyField(blank=True, null=True, related_name='room_requesters', to='base.guest'),
        ),
    ]
