# Generated by Django 4.2.5 on 2023-09-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_home_requestslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='num',
        ),
        migrations.RemoveField(
            model_name='completedmatch',
            name='num',
        ),
        migrations.RemoveField(
            model_name='home',
            name='num',
        ),
        migrations.RemoveField(
            model_name='like',
            name='num',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='num',
        ),
        migrations.RemoveField(
            model_name='match',
            name='num',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='num',
        ),
        migrations.RemoveField(
            model_name='pairrequest',
            name='num',
        ),
        migrations.RemoveField(
            model_name='pwdreset',
            name='num',
        ),
        migrations.RemoveField(
            model_name='review',
            name='num',
        ),
        migrations.RemoveField(
            model_name='signinlog',
            name='num',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='actId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='completedmatch',
            name='cmId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guestId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='hbId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='homeId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mailId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='pairrequest',
            name='rqstId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='pwdreset',
            name='resetId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='roomphoto',
            name='photoId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='signinlog',
            name='loginId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UID',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='photoId',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
